version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:5173
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_SERVER_URL=http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 