name: Scriptocol CI

on:
  push:
    branches:
      - main  # This will trigger the workflow on any push to the main branch
  workflow_dispatch:  # This will allow you to trigger the workflow manually
    inputs:
      commitId:
        description: 'Commit ID for the workflow'
        required: true
        type: string

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Language
        id: detect-lang
        run: |
          if [ -f "package.json" ]; then
            echo "lang=js" >> $GITHUB_ENV
          elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
            echo "lang=python" >> $GITHUB_ENV
          elif [ -f "go.mod" ]; then
            echo "lang=go" >> $GITHUB_ENV
          else
            echo "Unsupported language" && exit 1
          fi

      - name: Set up Environment
        run: |
          case "$lang" in
            js)
              echo "Setting up Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs
              npm install
              ;;
            python)
              echo "Setting up Python..."
              python -m venv venv && source venv/bin/activate
              pip install -r requirements.txt
              ;;
            go)
              echo "Setting up Go..."
              wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
              tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz
              export PATH=$PATH:/usr/local/go/bin
              go mod tidy
              ;;
          esac

      - name: Run Tests
        id: test-results
        continue-on-error: true
        run: |
          case "$lang" in
            js) npm test || echo "Tests failed" ;;
            python) pytest || echo "Tests failed" ;;
            go) go test ./... || echo "Tests failed" ;;
          esac

      - name: Create Fix Branch
        if: env.FIXES_COUNT > 0
        run: |
          git config --global user.name "Scriptocol Bot"
          git config --global user.email "bot@scriptocol.com"
          COMMIT_SHA=$(git rev-parse HEAD)
          BRANCH_NAME="fix/${COMMIT_SHA:0:7}"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.FIXES_COUNT > 0
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "[Scriptocol] Automated fixes"
          title: "[Scriptocol] Automated fixes"
          body: |
            This PR contains automated fixes generated by Scriptocol.
            
            Original commit: ${{ github.sha }}
            Language: ${{ env.lang }}
            Number of fixes: ${{ env.FIXES_COUNT }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: |
            automated-pr
            scriptocol
